#+TITLE: GregoLy
#+AUTHOR: Alex Harter
#+TODO: TODO DEBUG | WAIT DONE
* Notes
** Why use literate programming for this project?
- mixing multiple formats
- targetting graphical output
- personal project
- linking to documentation
- presentation
* Log
** Ryan's Advice <2024-12-09>
#+BEGIN_QUOTE
Re: Does anyone have general advice on text parsing for converting between two text formats?
If you are converting between two formats, then first notice that these formats must have some shared /abstract/ definition.
Your goal is to write a parser for one text format, which produces information encoded in that share abstract format.
Then to write a generator, which takes that shared abstract format as input, and produces text as output.
#+END_QUOTE
- In general, LilyPond is a superset of Gregorio, so all the shared information will come from gabc
* src
#+PROPERTY: header-args python :tangle gregoly.py
** lilypond template
- [[https://lilypond.org/doc/v2.24/Documentation/notation/the-emmentaler-font#vaticana-glyphs][LilyPond Emmentaler Font Reference]]
#+BEGIN_SRC lilypond :tangle template.ly
  \version "2.24.4"

  \header {
    %ly_metadata
  }

  oriscus = {
    %default_oriscus
    \once \override NoteHead.stencil = #ly:text-interface::print
    \once \override NoteHead.text = \markup \musicglyph "noteheads.ssolesmes.oriscus"
    \once \set fontSize = 3
    %end
  }

  quilisma = {
    %default_quilisma
    \once \override NoteHead.stencil = #ly:text-interface::print
    \once \override NoteHead.text = \markup \musicglyph "noteheads.svaticana.quilisma"
    \once \set fontSize = 3
    \once \override Stem.transparent = ##t
    %end
  }

  initioDebilis = {
    %default_initioDebilis
    \once \set fontSize = -3
    \once \override Stem.transparent = ##t
    %end
  }

  liquescentDiminutive = {
    \once \set fontSize = -3
  }

  liquescentAugmentativeAscending = {
    \once \override NoteHead.stencil = #ly:text-interface::print
    \once \override NoteHead.text = \markup \musicglyph "noteheads.ssolesmes.auct.asc"
    \once \set fontSize = 3
  }

  liquescentAugmentativeDescending = {
    \once \override NoteHead.stencil = #ly:text-interface::print
    \once \override NoteHead.text = \markup \musicglyph "noteheads.ssolesmes.auct.desc"
    \once \set fontSize = 3
  }

  quarterBar = {
    \bar ","
  }

  halfBar = {
    \bar ";"
  }

  fullBar = {
    \bar "|"
  }

  doubleBar = {
    \finalis
  }

  global = {
    \key c \major
    \candenzaOn
    \omit Staff.TimeSignature
    \override Staff.StaffSymbol.color = #darkred
  }

  melody = \transpose c c \relative c'' {
    \global

    %ly_melody
  }

  text = \lyricmode {
    %ly_lyrics
  }

  \score {
    <<
    \new Staff {
      \context Voice = "vocal" { \melody }
    }
    \new Lyrics \lyricsto "vocal" \text
    >>
    \layout {
      \context {
	\Staff
	%annotation
	\consists Custos_engraver
	\override Custos.style = #'medicaea
      }
    }
  }
  % score generated from https://github.com/AlexHarter/GregoLy on <%DATE>
#+END_SRC
** main input
- accept user input, call parsing and formatting functions, customize output
- arguments
  - /path/to/file.gabc
  - in which rhythmic system to interpret
    - "P" *P*roportional
    - "S" Classical *S*olesmes
    - "V" *V*atican 
  - key (default: as close to C4-C5 as possible, within two accidentals)
  - interpretive options
    - presence of special neumes (default: yes to all)
    - explicit notation of special neumes (default: neume noteheads)
  - aesthetic options
    - presence of custodes (default: yes)
    - staff color (default: dark red)
#+BEGIN_SRC python
  print("Importing modules...")
  import argparse
  import re
  import cython
  from datetime import datetime
  import subprocess

  print("Processing user arguments...")
  parser = argparse.ArgumentParser(description="Process some mutually exclusive flags.")
  group = parser.add_mutually_exclusive_group(required=False)

  group.add_argument("-P", "--proportional", action="store_true", help="Proportional Mode")
  group.add_argument("-S", "--solesmes", action="store_true", help="Solesmes Mode")
  group.add_argument("-V", "--vatican", action="store_true", help="Vatican Mode")

  parser.add_argument("-f", "--file", type=str, help="Path to the input file")

  args = parser.parse_args()

  if not (args.solesmes or args.vatican):
      args.proportional = True

  if args.proportional:
      print("Proportional option is enabled.\n")
  elif args.solesmes:
      print("Classical Solesmes option is enabled.\n")
  elif args.vatican:
      print("Vatican Edition option is enabled.\n")
  else:
      print("Proportional option is enabled. (default)\n")

  if args.file:
      print(f"Using input file: {args.file}")
  else:
      print("No input file specified.")

  print("Importing .gabc file...")
  with open(args.file, 'r') as file:
      gabc = file.read()

  print(f"Full GABC:\n{gabc}")

  if "%%" is in gabc:
      print("Splitting gabc file")
      gabc_header = gabc.split("%%")[0]
      gabc_body = gabc.split("%%")[1]
  else: print("No header detected.")

  print(f"GABC Header:\n{gabc_header}")
  print(f"GABC Body:\n{gabc_body}")
#+END_SRC
** gabc parsing
*** header
- [[https://gregorio-project.github.io/gabc/index.html#header][Gregorio Documentation]]
**** Example Header
#+BEGIN_SRC gabc :tangle no
  name: incipit;
  gabc-copyright: copyright on this gabc file;
  score-copyright: copyright on the source score;
  office-part: introitus/...;
  occasion: in church calendar;
  meter: for metrical hymns;
  commentary: source of words;
  arranger: name of arranger;
  author: if known;
  date: xi c;
  manuscript: ms name;
  manuscript-reference: e.g. CAO reference;
  manuscript-storage-place: library/monastery;
  book: from which score taken;
  language: of the lyrics;
  transcriber: writer of gabc;
  transcription-date: 2009;
  mode: 6;
  user-notes: whatever other comments you wish to make;
  annotation: IN.;
  annotation: 6;
  %%
#+END_SRC
**** Code
#+BEGIN_SRC python
  print("Parsing header...")

  gabc_header_lines = gabc_header.split(";\n")
  if gabc_header_lines[-1] == '':
      gabc_header_lines.pop(-1)

  header_entries = {}
  for line in gabc_header_lines:
      key, value = entry.split(":", 1) # in case there are colons in the value
      header_entries.update({key.strip(): value.strip()})
#+END_SRC
*** body
**** gabc body example
#+BEGIN_SRC gabc :tangle no
  (c4) DE(gj)us(jjj_) Is(h_)ra(h_0!iWj_//kjjo_)el(ji__) *(,)
  con(gh~)jún(hjij)gat(ih~) vos,(h_) (;)
  et(g_) i(h_)pse(g_) sit(gfh_) vo(h_)bís(h_0!iwji.__H~rG~rhv_)cum,(hg.__) (;)
  qui(gh/ji) mi(j_)sér(j_)tus(jjj_) est(h_) (;)
  du(h_)ó(h_)bus(hfh_) ú(h_//ivHG_0)ni(hg)cis:(g._) (;)
  et(g_) nunc,(hj) Dó(i_//jjg_//h_//jjh_)mi(hf__!gwhgh_)ne,(hg__) (;)
  fac(g_) e(-gh_)os(h_) plé(h_0!iWj_)ni(g_)us(gh__) (;) be(f_)ne(f_)dí(efOh_)ce(h_)re(gf__//hvGF_0gv_) te.(e._) <i>T. P.</i>(::)
  Al(e<_)le(f_)lú(gf~)ia.(g_) (;) al(gf~)le(ge__/f_0!gwhg__)lú(ghghFD__!eWf_//ge~)ia.(e._) (::)
  <i>Ps.</i> Be(g)á(hi)ti(i_) o(i_)mnes(i_) qui(j_) ti(k_)ment(j_) Dó(j_)mi(ih)num :(jjj._) *(:)
  qui(hg) ám(hi~)bu(i_)lant(i_) in(jjji) vi(hg)is(h_) e(i>_)jus.(gOh.__) (::) Gló(g_)ri(hi)a(i_) Pa(i_)tri...(i_) (::)
  Spi(j_)rí(k_)tu(j_)i(j_) San(ih~)cto...(jjj._) (::) Et(j_) nunc,(k_) et(j_) sem(ih~)per...(jjj._) (::)
  E(i_) u(jjji) o(hg) u(h_) a(i_) e.(gOh._) (::)
#+END_SRC
**** code
#+BEGIN_SRC python
import re
gabc_body = r"""
(c4) DE(gj)us(jjj_) Is(h_)ra(h_0!iWj_//kjjo_)el(ji__) *(,)
con(gh~)jún(hjij)gat(ih~) vos,(h_) (;)
et(g_) i(h_)pse(g_) sit(gfh_) vo(h_)bís(h_0!iwji.__H~rG~rhv_)cum,(hg.__) (;)
qui(gh/ji) mi(j_)sér(j_)tus(jjj_) est(h_) (;)
du(h_)ó(h_)bus(hfh_) ú(h_//ivHG_0)ni(hg)cis:(g._) (;)
et(g_) nunc,(hj) Dó(i_//jjg_//h_//jjh_)mi(hf__!gwhgh_)ne,(hg__) (;)
fac(g_) e(-gh_)os(h_) plé(h_0!iWj_)ni(g_)us(gh__) (;) be(f_)ne(f_)dí(efOh_)ce(h_)re(gf__//hvGF_0gv_) te.(e._) <i>T. P.</i>(::)
Al(e<_)le(f_)lú(gf~)ia.(g_) (;) al(gf~)le(ge__/f_0!gwhg__)lú(ghghFD__!eWf_//ge~)ia.(e._) (::)
<i>Ps.</i> Be(g)á(hi)ti(i_) o(i_)mnes(i_) qui(j_) ti(k_)ment(j_) Dó(j_)mi(ih)num :(jjj._) *(:)
qui(hg) ám(hi~)bu(i_)lant(i_) in(jjji) vi(hg)is(h_) e(i>_)jus.(gOh.__) (::) Gló(g_)ri(hi)a(i_) Pa(i_)tri...(i_) (::)
Spi(j_)rí(k_)tu(j_)i(j_) San(ih~)cto...(jjj._) (::) Et(j_) nunc,(k_) et(j_) sem(ih~)per...(jjj._) (::)
E(i_) u(jjji) o(hg) u(h_) a(i_) e.(gOh._) (::)
"""
clefs = ("c4", "c3", "c2", "c1", "f4", "f3", "f2", "f1", "cb4", "cb3", "cb2", "cb1")

note_positions = ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m")
note_kinds = ("punctum", "hollow_punctum", "quilisma", "oriscus", "quarter_bar", "half_bar", "full_bar", "double_bar")
note_liquescence = (None, "augmentative_ascending", "augmentative_descending", "diminutive")
note_lengthening = (None, "episema", "morae")

class Note:
    def __init__(self,
                 kind = "punctum",
                 clef = "c4",
                 position = None,
                 lengthening = None,
                 liquescence = None):

        self.kind = kind
        self.clef = clef
        self.position = position
        self.lengthening = lengthening
        self.liquescence = liquescence

        def __str__(self):
            return f"{self.kind}{self.clef}{self.position}{self.lengthening}{self.liquescence}"

class Syllable:
    def __init__(self,
                 text = "",
                 tie = True):
        self.text = text
        self.tie = tie

melody = []
lyrics = []
clef = "c4" # default if not defined

for i, c in enumerate(gabc_body):
    match c.lower():
        case "(":
            parsing_mode = "melody"
        case ")":
            parsing_mode = "lyrics"
        case "c": # characters a clef could start with
            if gabc_body[i:i+1] in clefs:
            clef = gabc_body[i:i+1]
        case "f":
            if gabc_body[i:i+1] in clefs:
            clef = gabc_body[i:i+1]
            case "g":
            note = Note(clef=clef,position=c)
            melody.append(note)

        case _:
            syllable = Syllable(text=c)

print(melody)
print(lyrics)
#+END_SRC
** lilypond formatting
*** metadata
*** melody
- this will probably be the most challenging part of the whole project
**** Data Sets
- gabc notates position on a staff rather than absolute pitches, so that's the main conversion I have to do for lilypond
#+BEGIN_SRC python
  gabc_positions_with_position_ints = {
      "a": 0,
      "b": 1,
      "c": 2,
      "d": 3,
      "e": 4,
      "f": 5,
      "g": 6,
      "h": 7,
      "i": 8,
      "j": 9,
      "k": 10,
      "l": 11,
      "m": 12
  }
  gabc_positions = gabc_positions_with_position_ints.keys()
  clefs_with_position_int_of_do = {
      "c1": 3,
      "c2": 5,
      "c3": 7,
      "c4": 9,
      "f1": 0,
      "f2": 2,
      "f3": 4,
      "f4": 6
  }
  clefs = clefs_with_position_int_of_do.keys()
  distance_from_do_with_ly_pitch_classes = {
      -9: "a",
      -8: "b",
      -7: "c",
      -6: "d",
      -5: "e",
      -4: "f",
      -3: "g",
      -2: "a",
      -1: "b",
       0: "c",
       1: "d",
       2: "e",
       3: "f",
       4: "g",
       5: "a",
       6: "b"
  }
#+END_SRC
**** Functions
#+BEGIN_SRC python
  def gabc_position_to_ly_pitch_class(clef, gabc_position):
    distance_from_do = gabc_positions_with_position_ints[gabc_position] - clefs_with_position_int_of_do[clef]
    ly_pitch_class = distance_from_do_with_ly_pitch_classes[distance_from_do]
    return ly_pitch_class
  #test
  print(gabc_position_to_ly_pitch_class("c4", "i"))
#+END_SRC** main output
#+BEGIN_SRC python
  ly_template_interpolated = ly_template
  ly_template_interpolated = ly_template_interpolated.replace("%ly_metadata", ''.join(ly_metadata))
  ly_template_interpolated = ly_template_interpolated.replace("%ly_melody", ly_melody)
  ly_template_interpolated = ly_template_interpolated.replace("%ly_lyrics", ly_lyrics)
  ly_template_interpolated = ly_template_interpolated.replace(
      "%annotation", 
      f"instrumentName = {gabc_header_dictionary['annotation']}")
  date = datetime.now().strftime("%Y-%m-%d")
  ly_template_interpolated = ly_template_interpolated.replace("%DATE", date)

  with open("target/chant.ly", "w") as file:
      file.write(ly_template_interpolated)
  print(ly_template_interpolated)
  ## Compile .ly file using lilypond cli
  subprocess.run(['lilypond' 'chant.ly'])
#+END_SRC
* tests
* [[file:demo.org][demo]]
